version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    nodejs: "14"
  commands:
    - pip install uv
    - uv sync
    - npm ci
    - uv run npm run build-html
    - mkdir -p _readthedocs/html/
    - cp -r output/* _readthedocs/html/
